Bump github.com/santhosh-tekuri/jsonschema/v6 from 6.0.1 to 6.0.2 (#857)
Bumps
[github.com/santhosh-tekuri/jsonschema/v6](https://github.com/santhosh-tekuri/jsonschema)
from 6.0.1 to 6.0.2.
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/santhosh-tekuri/jsonschema/commit/29cbed948d24a04700eb94436416b18a07953b71"><code>29cbed9</code></a>
release: v6.0.2</li>
<li><a
href="https://github.com/santhosh-tekuri/jsonschema/commit/82f39949fd9e41bf4a0fdaf1dc7f981148fa48a3"><code>82f3994</code></a>
OutputError: add String method</li>
<li><a
href="https://github.com/santhosh-tekuri/jsonschema/commit/4bdfd367e11af3aafedff994730d7216b809ffa6"><code>4bdfd36</code></a>
Types: export Add method</li>
<li><a
href="https://github.com/santhosh-tekuri/jsonschema/commit/0bd9d0e46bf598c2d829c428a101eac7a4160111"><code>0bd9d0e</code></a>
lint: migrate golangci.yml</li>
<li><a
href="https://github.com/santhosh-tekuri/jsonschema/commit/174b1cc8d57c4c35f09189a05215713981f056fe"><code>174b1cc</code></a>
validation: quote keyword in error msg</li>
<li><a
href="https://github.com/santhosh-tekuri/jsonschema/commit/83a4c8009c0e7855accffc926454a37a51d895ad"><code>83a4c80</code></a>
tests: update SON-Schema-Test-Suite</li>
<li><a
href="https://github.com/santhosh-tekuri/jsonschema/commit/0c7d0585e9ead4865ccccdc4434939b34a3710ef"><code>0c7d058</code></a>
docs: correct spelling</li>
<li><a
href="https://github.com/santhosh-tekuri/jsonschema/commit/728d843cd85dff30ca3545bbabf2462502114487"><code>728d843</code></a>
tests: update JSON-Schema-Test-Suite</li>
<li><a
href="https://github.com/santhosh-tekuri/jsonschema/commit/c54d5e38ee3f51183dd589ad397e2cc3d1b5ca3d"><code>c54d5e3</code></a>
tests: update JSON-Schema-Test-Suite</li>
<li><a
href="https://github.com/santhosh-tekuri/jsonschema/commit/86cca28795c9e34c43371b70608d243667bee2a9"><code>86cca28</code></a>
compile/fix: panic compiling non jsonschema resource</li>
<li>Additional commits viewable in <a
href="https://github.com/santhosh-tekuri/jsonschema/compare/v6.0.1...v6.0.2">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=github.com/santhosh-tekuri/jsonschema/v6&package-manager=go_modules&previous-version=6.0.1&new-version=6.0.2)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>