Improve error messages when `pgroll init` has not been run (#745)
Improve the error messages displayed by the CLI when attempting to run
commands that require `pgroll init` to have been run.

Old example of `pgroll start` before `pgroll init`:

```
ERROR   Failed to start migration: pq: schema "pgroll" does not exist
```

New error message:

```
Error: pgroll is not initialized, run 'pgroll init' to initialize
```

The same change is applied to all other commands that need to run
against an initialized database.

Closes https://github.com/xataio/pgroll/issues/723